### Project specific config ###
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN="1"
    - COMPOSER_OAUTH_TOKEN="cc4a091c096e7d3cfe053c3f669fb840be60ab98"

matrix:
  include:
    - os: linux
      language: php
      php: 7.1
      env:
        - ATOM_CHANNEL=stable
        - PHPCS_VER="1.*"

    - os: linux
      language: php
      php: 7.1
      env:
        - ATOM_CHANNEL=stable
        - PHPCS_VER="<2.6"

    - os: linux
      language: php
      php: 7.1
      env:
        - ATOM_CHANNEL=stable
        - PHPCS_VER="2.6.1"

    - os: linux
      language: php
      php: 7.1
      env:
        - ATOM_CHANNEL=stable
        - PHPCS_VER="2.*"

    - os: linux
      language: php
      php: 7.1
      env:
        - ATOM_CHANNEL=stable
        - PHPCS_VER="3.0.0"

    - os: linux
      language: php
      php: 5.6
      env:
        - ATOM_CHANNEL=stable
        - PHPCS_VER="*"

    - os: linux
      language: php
      php: 7.0
      env:
        - ATOM_CHANNEL=stable
        - PHPCS_VER="*"

    - os: linux
      language: php
      php: 7.1
      env:
        - ATOM_CHANNEL=stable
        - PHPCS_VER="*"

    - os: linux
      language: php
      php: 7.1
      env:
        - ATOM_CHANNEL=beta
        - PHPCS_VER="*"

install:
  # Set the GitHub OAuth token for Composer
  - composer config -g github-oauth.github.com "$COMPOSER_OAUTH_TOKEN"
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  # Install PHPCS
  - composer global require "squizlabs/php_codesniffer $PHPCS_VER"

before_script:
  - phpcs --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: "trusty"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - fakeroot
    - git
    - libsecret-1-dev
